### ISSUE TITLE
Uninitialized constant Contracts::Modules (NameError)

### ISSUE THREAD

**Issue by jawshooah** [mcandre/specs#33]
I have specs 0.20 installed with Ruby 2.3.0. Getting the following error anytime I run `specs`, regardless of the arguments:

```
$ specs --version
/Users/joshuahagins/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/specs-0.20/lib/specs.rb:35:in `<module:Os>': uninitialized constant Contracts::Modules (NameError)
Did you mean?  Module
	from /Users/joshuahagins/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/specs-0.20/lib/specs.rb:34:in `<top (required)>'
	from /Users/joshuahagins/.rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/joshuahagins/.rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/joshuahagins/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/specs-0.20/bin/specs:2:in `<top (required)>'
	from /Users/joshuahagins/.rbenv/versions/2.3/bin/specs:23:in `load'
	from /Users/joshuahagins/.rbenv/versions/2.3/bin/specs:23:in `<main>'
```

**Comment by jawshooah** [comment]
And with Homebrew-installed Ruby:

```
$ specs --version
/usr/local/lib/ruby/gems/2.3.0/gems/specs-0.20/lib/specs.rb:35:in `<module:Os>': uninitialized constant Contracts::Modules (NameError)
Did you mean?  Module
	from /usr/local/lib/ruby/gems/2.3.0/gems/specs-0.20/lib/specs.rb:34:in `<top (required)>'
	from /usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/lib/ruby/gems/2.3.0/gems/specs-0.20/bin/specs:2:in `<top (required)>'
	from /usr/local/bin/specs:23:in `load'
	from /usr/local/bin/specs:23:in `<main>'
```

And with system Ruby:

```
$ /usr/bin/specs --version
/Library/Ruby/Gems/2.0.0/gems/specs-0.20/lib/specs.rb:35:in `<module:Os>': uninitialized constant Contracts::Modules (NameError)
	from /Library/Ruby/Gems/2.0.0/gems/specs-0.20/lib/specs.rb:34:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/specs-0.20/bin/specs:2:in `<top (required)>'
	from /usr/bin/specs:23:in `load'
	from /usr/bin/specs:23:in `<main>'
```

**Comment by mcandre** [comment]
Yep.

I made the mistake of letting the Contracts version float; it's not yet v1.0 so the API often breaks.

I'll forcibly downgrade Contracts until specs works again, and publish a new version of specs.

**Comment by mcandre** [comment]
Never a dull moment. specs v 0.21 is apparently 'up' now on RubyGems, but when I try to actually gem install it, gem can't find it.

https://github.com/rubygems/rubygems.org/issues/1158

**Comment by mcandre** [comment]
Published. Run `gem install specs -v 0.21` to upgrade.

**Comment by jawshooah** [comment]
Fixed, thanks!
